behaviors:
  ChessBot:
    trainer_type: ppo  # You can switch to poca if needed for competitive play
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    self_play:  # Enable this section if you have an adversarial game
      window: 10  # Number of past versions to store
      play_against_latest_model_ratio: 0.5  # Probability of playing against latest model
      save_steps: 10000  # How often to save past versions

    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000